version: 1.0.0
slice_name: Xuat khau vs Nhap khau theo Ky (Chi tiet Hai quan)
viz_type: dist_bar
params:
  adhoc_filters: []
  groupby:
  - period_label
  metrics:
  - aggregate: MAX
    column:
      column_name: export_value
      type: FLOAT
    expressionType: SIMPLE
    label: Xuat khau
    optionName: metric_max_export
  - aggregate: MAX
    column:
      column_name: import_value
      type: FLOAT
    expressionType: SIMPLE
    label: Nhap khau
    optionName: metric_max_import
  row_limit: 20
  show_legend: true
  order_desc: false
  x_axis_label: ""
  y_axis_label: Gia tri (ty USD)
  y_axis_bounds:
  - 0
  - null
  viz_type: dist_bar
dataset_uuid: 44b8f6ce-d922-4857-8478-41d81a929220
uuid: 44b8f6ce-d922-4857-8478-41d81a929204
