version: 1.0.0
slice_name: So sánh Kim ngạch Xuất khẩu và Nhập khẩu (Hải quan)
viz_type: dist_bar
params:
  adhoc_filters:
  - clause: WHERE
    expressionType: SQL
    sqlExpression: "period LIKE '%(tỷ USD)'"
  - clause: WHERE
    expressionType: SQL
    sqlExpression: "category IN ('Xuất khẩu','Nhập khẩu')"
  columns:
  - category
  groupby:
  - period
  metrics:
  - aggregate: MAX
    column:
      column_name: value_usd
      type: FLOAT
    expressionType: SIMPLE
    label: MAX(value_usd)
    optionName: metric_max_value
  row_limit: 500
  show_legend: true
  x_axis_label: Giai đoạn báo cáo
  y_axis_label: Giá trị (tỷ USD)
  viz_type: dist_bar
dataset_uuid: 44b8f6ce-d922-4857-8478-41d81a929113
uuid: 44b8f6ce-d922-4857-8478-41d81a929117