version: 1.0.0
slice_name: So sánh Lãi suất Tiền gửi các Ngân hàng (12 tháng)
viz_type: dist_bar
params:
  adhoc_filters:
  - clause: WHERE
    expressionType: SQL
    sqlExpression: "term = '12 tháng'"
  columns:
  - term
  groupby:
  - bank_name
  metrics:
  - aggregate: MAX
    column:
      column_name: rate
      type: FLOAT
    expressionType: SIMPLE
    label: MAX(rate)
    optionName: metric_rate_12m
  row_limit: 50
  show_legend: false
  x_axis_label: Ngân hàng
  y_axis_label: "Lãi suất (%/năm)"
  color_scheme: googleCategory10c
  viz_type: dist_bar
dataset_uuid: 44b8f6ce-d922-4857-8478-41d81a929113
uuid: 44b8f6ce-d922-4857-8478-41d81a929149
