version: 1.0.0
slice_name: Biến động Giá Cổ phiếu Ngân hàng & BĐS
viz_type: echarts_timeseries_line
params:
  adhoc_filters:
  - clause: WHERE
    expressionType: SQL
    sqlExpression: "symbol IN ('VCB','BID','CTG','MBB','ACB','TCB','VPB','STB','LPB','HDB','SSB','SHB','EIB','TPB','VIB','OCB','MSB','BAB','NAB','KLB','SGB','NVB','BVB','VAB')"
  time_range: No filter
  groupby:
  - symbol
  metrics:
  - aggregate: AVG
    column:
      column_name: gia_dong_cua
      type: FLOAT
    expressionType: SIMPLE
    label: Giá đóng cửa TB
    optionName: metric_avg_price
  granularity_sqla: ngay
  series_type: line
  time_grain_sqla: P1D
  row_limit: 50000
  x_axis_label: Thời gian
  y_axis_label: Giá (VND)
dataset_uuid: 5518f6ce-d922-4857-8478-41d81a929212
uuid: 5518f6ce-d922-4857-8478-41d81a929201
