version: 1.0.0
slice_name: Danh sách Tin tức Ngành Dệt may mới nhất
viz_type: table
params:
  adhoc_filters: []
  columns:
  - published_date
  - title
  - url
  groupby: []
  metrics: []
  row_limit: 20
  viz_type: table
dataset_uuid: 44b8f6ce-d922-4857-8478-41d81a929120
uuid: 44b8f6ce-d922-4857-8478-41d81a929121
