version: 1.0.0
slice_name: Diễn biến Kim ngạch Hải quan theo Danh mục
viz_type: echarts_timeseries_line
params:
  adhoc_filters: []
  groupby:
  - category
  metrics:
  - expression: SUM(value_usd)
    label: Kim ngạch
  series_type: line
  time_grain_sqla: P1M
  viz_type: echarts_timeseries_line
  x_axis_label: Thời gian
  y_axis_label: Giá trị (USD)
dataset_uuid: 1318f6ce-d922-4857-8478-41d81a929115
uuid: 1318f6ce-d922-4857-8478-41d81a929123
