version: 1.0.0
slice_name: "Bi\u1EBFn \u0111\u1ED9ng Gi\xE1 C\u1ED5 phi\u1EBFu Ng\xE2n h\xE0ng & B\u0110S"
viz_type: echarts_timeseries_line
params:
  adhoc_filters: []
  groupby:
  - symbol
  metrics:
  - expression: AVG(gia_dong_cua)
    label: "Gi\xE1 \u0111\xF3ng c\u1EEDa TB"
  series_type: line
  time_grain_sqla: P1D
  x_axis_label: "Th\u1EDDi gian"
  y_axis_label: "Gi\xE1 (VN\u0110)"
dataset_uuid: 78b8f0e6-46d3-405c-9c95-529931613a26
uuid: 3848a129-1867-4898-8e65-3b4659771474
